defaults:
  - _self_
  - model: mobilevit
  - dataset: pamap2_dataset
  - strategy: clean
  - hparams_search: null
# Training Hyperparameters
epochs: 50
batch_size: 32
lr: 0.001
weight_decay: 0.0001
patience: 20
aux_weight: 0.4

# Experiment Settings
results_dir: "results/PAMAP2/clean"
seed: 42
limit_folds: null
resume_dir: null
tune_mode: False
